version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    stdin_open: true
    tty: true
    env_file:
      - ./scripts/.env.prod
    environment:
      - NODE_ENV=production
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 80:8765

  mongodb:
    image: 'bitnami/mongodb:3.6'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
